# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImagePickerAssignment' do
  use_frameworks!

  # Pods for ImagePickerAssignment
  # SnapKit
  pod 'SnapKit', '~> 3.1.2'
end
